create table if not exists public.places (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  category text check (category in ('coffee', 'food', 'books', 'art', 'outdoors', 'event')),
  lat double precision not null,
  lng double precision not null,
  price_level smallint check (price_level between 0 and 4),
  link text,
  location text,
  map_link text
);

alter table public.places enable row level security;
alter table public.places alter column category drop not null;

alter table public.places add column if not exists location text;
alter table public.places add column if not exists map_link text;
alter table public.places add column if not exists price_level smallint check (price_level between 0 and 4);

grant select, insert, update on table public.places to service_role;

create table if not exists public.unpinned (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  link text,
  name text,
  location text,
  category text,
  price_level smallint check (price_level between 0 and 4),
  lat double precision,
  lng double precision,
  map_link text
);

alter table public.unpinned add column if not exists name text;
alter table public.unpinned add column if not exists location text;
alter table public.unpinned add column if not exists category text;
alter table public.unpinned add column if not exists price_level smallint check (price_level between 0 and 4);
alter table public.unpinned add column if not exists lat double precision;
alter table public.unpinned add column if not exists lng double precision;
alter table public.unpinned add column if not exists map_link text;

grant select, insert on table public.unpinned to service_role;
