create table if not exists public.places (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  category text not null check (category in ('coffee', 'food', 'books', 'art', 'outdoors', 'event')),
  lat double precision not null,
  lng double precision not null,
  price_level smallint check (price_level between 0 and 4),
  link text,
  location text,
  map_link text
);

alter table public.places enable row level security;

alter table public.places add column if not exists location text;
alter table public.places add column if not exists map_link text;
alter table public.places add column if not exists price_level smallint check (price_level between 0 and 4);

grant select, insert, update on table public.places to service_role;
